brickObj = EV3();
brickObj.connect('usb');
hoehenmotor = brickObj.motorD;
hoehenmotor.power = -5;
hoehenmotor.speedRegulation = 'On';
hoehenmotor.brakeMode = 'Brake';
hoehenmotor.resetTachoCount;
hoehenmotor.limitValue = 160;
hoehenmotor.start;
hoehenmotor.waitFor;
brickObj.motorB.power = -10;
brickObj.motorB.limitValue = 730;
brickObj.motorB.start;
brickObj.motorB.waitFor;
brickObj.motorB.power = 10;
brickObj.motorB.limitValue = 730;
brickObj.motorB.start;
brickObj.motorB.waitFor;
brickObj.disconnect();